sudo: required

language: java

cache:
  directories:
  - "$HOME/.m2"

services:
  - docker

script:
  - mvn clean install -Ddocker.useColor=false -Ddocker.showLogs -Pdocker -Pjacoco coveralls:report
