zuul:
  routes:
    doorman:
      url: http://localhost:8082
      sensitiveHeaders:
    worker:
      url: http://localhost:8082
    beekeeper:
      url: http://localhost:8082

# disable netflix eurkea since it's not used for service discovery
ribbon:
  eureka:
    enabled: false